name: hello-world
on: push
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
