name: hello-world
on: push
jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
